name: End-to-end tests

'on': push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install cypress-visual-regression --save-dev
      
      - name: Install MysQL 
        run: npm i mysql -D   

      - name: Setup MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo mysql -e "CREATE DATABASE sql_hr;"
          sudo mysql -e "GRANT ALL PRIVILEGES ON sql_hr.* TO 'root'@'localhost' IDENTIFIED BY 'MySQL@123';"
          sudo systemctl restart mysql

      - name: Cypress run with Visual Regression
        run: npx cypress run --env visual_regression=true

      - uses: actions/upload-artifact@v4
        name: Add artifacts for Mochawesome report
        if: always()
        with:
          name: mochawesome-report
          path: cypress/reports/html/index.html
          retention-days: 30






