name: End-to-end tests
'on': push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v4
        if: always()
      - name: Add artifacts for Mochawesome report
      - uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome-report
          retention-days: 30
          
